### PR TITLE
chore(deps): updated openapi-response-validator to ^7.0.1 (was ^4.0.1)

### PR DESCRIPTION
**Pull request by mvegter**

### CODE REVIEW

**Comment by rwalle61** [comment]
Thanks! Will merge straight after the basePath PR is merged (very soon)

**Comment by rwalle61** [comment]
I just remembered that the latest version of openapi-response-validator has a different api, which broke us previously. Let me investigate when I have time

**Comment by mvegter** [comment]
@rwalle61 I have just rebased against latest master (includes the basePath PR). All checks have passed, let me know if you remember or figure out what the problem was.

**Comment by rwalle61** [comment]
@mvegter I think our yarn workspace isn't actually paying attention to the `package.json` of the `openapi-validator` submodule. For example, the [`yarn.lock` hasn't changed](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/yarn.lock#L4403). 

I think the fix is for me to make our `openapi-validator` a proper package listed in `packages`, so that we can reuse the code in the jest and chai plugins, and fix this package.json behaviour

**Comment by rwalle61** [comment]
hey @mvegter, we won't be able to merge this or https://github.com/RuntimeTools/OpenAPIValidators/pull/174 until we:
1. manually update the `yarn.lock`
2. fix our code to work with the latest version of `openapi-response-validator`, which breaks [these tests]() because the validation error does not include the names of the invalid properties

You may be able to install the latest version of `openapi-response-validator` by manually updating `openapi-validator`'s `package.json`, deleting the `node_modules`, then rerunning `yarn install`.

(To automate this, I will need to fix our yarn workspace configuration, which I will do at some point).

It'd be great if you could create an issue for this! You're very welcome to PR the fix too, and I'll happily guide you :)

Let me know so I know whether to keep these PRs open.

**Comment by mvegter** [comment]
@rwalle61 I'm going to give it a shot at fixing the packages. but no promises as my yarn knowledge is very limited.

**Pull request closed without merging**
